object Versions {
    val kotlin = "1.3.71"
    val coroutines = "1.3.3"

    val ktx = "1.2.0"
    val material = "1.2.0-alpha05"
    val appCompat = "1.1.0"
    val constraintLayout = "1.1.3"
    val lifecycle = "2.2.0"
    val fragment = "1.3.0-alpha04"
    val navigation = "2.3.0-alpha06"
    val uniflow = "0.11.0"
    val threeTen = "1.2.4"
    val mockk = "1.10.0"
    val permissionsDispatcher = "4.7.0"
    val room = "2.2.5"
    val epoxy = "4.0.0-beta2"
    val hilt = "2.28-alpha"
    val hiltJetpack = "1.0.0-alpha01"
    val testJetpack = "2.1.0"

    val flowPreferences = "1.1.1"
    val kaspresso = "1.1.0"
    val jakarta = "1.6.5"
    val truth = "1.2.0"
    val flowTest = "1.4.1"
}


object Deps {
    val kotlin = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.kotlin}"
    val coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.coroutines}"
    val appCompat = "androidx.appcompat:appcompat:${Versions.appCompat}"
    val ktx = "androidx.core:core-ktx:${Versions.ktx}"
    val viewModel = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.lifecycle}"
    val constraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.constraintLayout}"
    val material = "com.google.android.material:material:${Versions.material}"
    val navigationFragment = "androidx.navigation:navigation-fragment-ktx:${Versions.navigation}"
    val navigationUi = "androidx.navigation:navigation-ui-ktx:${Versions.navigation}"
    val uniflow = "io.uniflow:uniflow-android:${Versions.uniflow}"
    val hilt = "com.google.dagger:hilt-android:${Versions.hilt}"
    val hiltCompiler = "com.google.dagger:hilt-android-compiler:${Versions.hilt}"
    val hiltViewModel = "androidx.hilt:hilt-lifecycle-viewmodel:${Versions.hiltJetpack}"
    val hiltJetpackCompiler = "androidx.hilt:hilt-compiler:${Versions.hiltJetpack}"
    val threeTen = "com.jakewharton.threetenabp:threetenabp:${Versions.threeTen}"
    val jakarta = "com.sun.mail:android-mail:${Versions.jakarta}"
    val jakartaActivation = "com.sun.mail:android-activation:${Versions.jakarta}"
    val epoxy = "com.airbnb.android:epoxy:${Versions.epoxy}"
    val epoxyCompiler = "com.airbnb.android:epoxy-processor:${Versions.epoxy}"
    val roomRuntinme = "androidx.room:room-runtime:${Versions.room}"
    val roomCompiler = "androidx.room:room-compiler:${Versions.room}"
    val roomKtx = "androidx.room:room-ktx:${Versions.room}"
    val junit = "junit:junit:4.13"
    val uniflowTest = "io.uniflow:uniflow-test:${Versions.uniflow}"
    val uniflowAndroidTest = "io.uniflow:uniflow-android-test:${Versions.uniflow}"
    val coroutinesTest = "org.jetbrains.kotlinx:kotlinx-coroutines-test:${Versions.coroutines}"
    val mockk = "io.mockk:mockk:${Versions.mockk}"
    val junitInstrumentation = "androidx.test.ext:junit:1.1.1"
    val truth = "androidx.test.ext:truth:${Versions.truth}"
    val test = "androidx.arch.core:core-testing:${Versions.testJetpack}"
    val kluentAndroid = "org.amshove.kluent:kluent-android:${Versions.truth}"
    val espresso = "androidx.test.espresso:espresso-core:3.2.0"
    val kaspresso = "com.kaspersky.android-components:kaspresso:${Versions.kaspresso}"
    val navigationTest = "androidx.navigation:navigation-testing:${Versions.navigation}"
    val flowTest = "com.github.ologe:flow-test-observer:${Versions.flowTest}"
}
